### ISSUE TITLE
dodaj dodaj wsparcie do playlist

### ISSUE THREAD

**Issue by ihavenoclueastowhatputinhere** [drobotk/degenerat-bot#1]
`while True:
    print('bth')`

**Comment by ihavenoclueastowhatputinhere** [comment]
nie zamykaj przypadkiem tego

**Comment by ihavenoclueastowhatputinhere** [comment]
![nyba](https://user-images.githubusercontent.com/50261686/150597492-607ff71f-0bfb-4edd-bc99-3fe948c8a867.png)

**Comment by ihavenoclueastowhatputinhere** [comment]
![among-us-twerk](https://user-images.githubusercontent.com/50261686/150855381-5ee7ee83-7812-4cad-b091-265f1314db89.gif)

**Comment by drobotk** [comment]
Temat wałkowany milion razy. Zamykam

**Comment by ihavenoclueastowhatputinhere** [comment]
nie
